name: sembast_cache_manager
description: A Sembast-based cache manager for the NDK (Nostr Development Kit) library, providing persistent storage for Nostr protocol data.
version: 1.0.0
homepage: https://github.com/deeayeen/sembast_cache_manager
repository: https://github.com/deeayeen/sembast_cache_manager

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  ndk: ^0.4.0
  sembast: ^3.8.5+1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
